version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: arezoo1234
    ports:
      - 3307:3307