CREATE DATABASE IF NOT EXISTS eCommerce;
USE eCommerce;
DROP TABLE IF EXISTS products;
CREATE TABLE products
(
	id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name   VARCHAR(255) DEFAULT NULL,
	price       VARCHAR(255) DEFAULT NULL,
	imageUrl    VARCHAR(255) DEFAULT NULL,
    status      VARCHAR(30) DEFAULT NULL,
    createdAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) AUTO_INCREMENT = 1;